In [1]:
# ============================================
# M1.5 - DATASET INSPECTION
# AuthentiScore
# ============================================

import pandas as pd
import numpy as np
import os
import glob

In [2]:
# Path to the raw dataset

DATA_DIR = "../data/raw/instagram_fake_spammer"

print("Dataset directory:")
print(os.path.abspath(DATA_DIR))

Dataset directory:
c:\Users\Acer\Documents\AuthentiScore\data\raw\instagram_fake_spammer

In [4]:
# Check if dataset folder exists

if os.path.exists(DATA_DIR):
    print("✅ Dataset folder found!")
else:
    print("❌ Dataset folder NOT found.")
    print("Check the DATA_DIR path.")

✅ Dataset folder found!

In [5]:
# Display files inside the dataset folder

files = os.listdir(DATA_DIR)

print("Files found:")
print("----------------")

for file in files:
    print(file)

Files found:
----------------
test.csv
train.csv

In [6]:
# Find all CSV files

csv_files = glob.glob(os.path.join(DATA_DIR, "*.csv"))

print(f"Number of CSV files found: {len(csv_files)}")
print()

for file in csv_files:
    print(file)

Number of CSV files found: 2

../data/raw/instagram_fake_spammer\test.csv
../data/raw/instagram_fake_spammer\train.csv

In [7]:
# Check size of each CSV file

for file in csv_files:
    size_mb = os.path.getsize(file) / (1024 * 1024)

    print(f"{os.path.basename(file)} : {size_mb:.2f} MB")

test.csv : 0.00 MB
train.csv : 0.02 MB

In [8]:
TRAIN_PATH = os.path.join(DATA_DIR, "train.csv")

train_df = pd.read_csv(TRAIN_PATH)

print("✅ Training dataset loaded successfully!")

✅ Training dataset loaded successfully!

In [9]:
TEST_PATH = os.path.join(DATA_DIR, "test.csv")

if os.path.exists(TEST_PATH):

    test_df = pd.read_csv(TEST_PATH)

    print("✅ Test dataset loaded successfully!")

else:

    test_df = None

    print("⚠️ test.csv not found.")

✅ Test dataset loaded successfully!

In [10]:
print("Training Dataset Shape")
print("======================")
print(f"Rows    : {train_df.shape[0]}")
print(f"Columns : {train_df.shape[1]}")

Training Dataset Shape
======================
Rows    : 576
Columns : 12

In [11]:
if test_df is not None:

    print("Test Dataset Shape")
    print("==================")
    print(f"Rows    : {test_df.shape[0]}")
    print(f"Columns : {test_df.shape[1]}")

else:

    print("No separate test dataset found.")

Test Dataset Shape
==================
Rows    : 120
Columns : 12

In [12]:
train_df.head()

,profile pic,nums/length username,fullname words,nums/length fullname,name==username,description length,external URL,private,#posts,#followers,#follows,fake
0,1,0.27,0,0.0,0,53,0,0,32,1000,955,0
1,1,0.00,2,0.0,0,44,0,0,286,2740,533,0
2,1,0.10,2,0.0,0,0,0,1,13,159,98,0
3,1,0.00,1,0.0,0,82,0,0,679,414,651,0
4,1,0.00,2,0.0,0,0,0,1,6,151,126,0

In [13]:
train_df.tail()

,profile pic,nums/length username,fullname words,nums/length fullname,name==username,description length,external URL,private,#posts,#followers,#follows,fake
571,1,0.55,1,0.44,0,0,0,0,33,166,596,1
572,1,0.38,1,0.33,0,21,0,0,44,66,75,1
573,1,0.57,2,0.00,0,0,0,0,4,96,339,1
574,1,0.57,1,0.00,0,11,0,0,0,57,73,1
575,1,0.27,1,0.00,0,0,0,0,2,150,487,1

In [14]:
train_df.sample(
    min(10, len(train_df)),
    random_state=42
)

,profile pic,nums/length username,fullname words,nums/length fullname,name==username,description length,external URL,private,#posts,#followers,#follows,fake
234,1,0.17,2,0.00,0,134,1,0,31,265,321,0
118,1,0.00,0,0.00,0,123,1,0,107,971,2047,0
346,1,0.31,1,0.31,1,0,0,1,0,25,86,1
498,0,0.28,1,0.24,0,0,0,0,0,86,0,1
402,1,0.00,2,0.00,0,0,0,0,14,143,500,1
400,0,0.00,0,0.00,0,0,0,0,9,589,2980,1
259,1,0.00,2,0.00,0,23,0,0,85,668,609,0
29,1,0.00,2,0.00,0,122,0,1,15,186,174,0
82,1,0.00,3,0.00,0,70,1,0,227,17303,360,0
380,1,0.12,1,0.00,0,91,0,0,7,38,87,1

In [15]:
print("Column Names")
print("============")

for i, column in enumerate(train_df.columns, start=1):
    print(f"{i}. {column}")

Column Names
============
1. profile pic
2. nums/length username
3. fullname words
4. nums/length fullname
5. name==username
6. description length
7. external URL
8. private
9. #posts
10. #followers
11. #follows
12. fake

In [16]:
print("Number of columns:", len(train_df.columns))

Number of columns: 12

In [17]:
print("Data Types")
print("==========")

print(train_df.dtypes)

Data Types
==========
profile pic               int64
nums/length username    float64
fullname words            int64
nums/length fullname    float64
name==username            int64
description length        int64
external URL              int64
private                   int64
#posts                    int64
#followers                int64
#follows                  int64
fake                      int64
dtype: object

In [18]:
print("Dataset Information")
print("===================")

train_df.info()

Dataset Information
===================
<class 'pandas.DataFrame'>
RangeIndex: 576 entries, 0 to 575
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   profile pic           576 non-null    int64
 1   nums/length username  576 non-null    float64
 2   fullname words        576 non-null    int64
 3   nums/length fullname  576 non-null    float64
 4   name==username        576 non-null    int64
 5   description length    576 non-null    int64
 6   external URL          576 non-null    int64
 7   private               576 non-null    int64
 8   #posts                576 non-null    int64
 9   #followers            576 non-null    int64
 10  #follows              576 non-null    int64
 11  fake                  576 non-null    int64
dtypes: float64(2), int64(10)
memory usage: 54.1 KB

In [19]:
missing_values = train_df.isnull().sum()

print("Missing Values")
print("==============")

print(missing_values)

Missing Values
==============
profile pic             0
nums/length username    0
fullname words          0
nums/length fullname    0
name==username          0
description length      0
external URL            0
private                 0
#posts                  0
#followers              0
#follows                0
fake                    0
dtype: int64

In [20]:
missing_percentage = (
    train_df.isnull().sum()
    / len(train_df)
    * 100
)

missing_report = pd.DataFrame({
    "Missing Count": train_df.isnull().sum(),
    "Missing Percentage": missing_percentage
})

missing_report

                      Missing Count  Missing Percentage
profile pic                       0                 0.0
nums/length username              0                 0.0
fullname words                    0                 0.0
nums/length fullname              0                 0.0
name==username                    0                 0.0
description length                0                 0.0
external URL                      0                 0.0
private                           0                 0.0
#posts                            0                 0.0
#followers                        0                 0.0
#follows                          0                 0.0
fake                              0                 0.0

In [21]:
duplicate_count = train_df.duplicated().sum()

print("Duplicate Rows:", duplicate_count)

Duplicate Rows: 2

In [22]:
duplicates = train_df[train_df.duplicated(keep=False)]

print("Number of rows involved in duplicates:", len(duplicates))

duplicates.head(20)

Number of rows involved in duplicates: 4

,profile pic,nums/length username,fullname words,nums/length fullname,name==username,description length,external URL,private,#posts,#followers,#follows,fake
196,1,0.00,2,0.0,0,48,0,0,222,5282,652,0
197,1,0.00,2,0.0,0,48,0,0,222,5282,652,0
491,1,0.91,1,0.0,0,0,0,0,0,75,26,1
525,1,0.91,1,0.0,0,0,0,0,0,75,26,1

In [23]:
unique_report = pd.DataFrame({
    "Column": train_df.columns,
    "Unique Values": [
        train_df[column].nunique()
        for column in train_df.columns
    ]
})

unique_report

                  Column  Unique Values
0            profile pic              2
1   nums/length username             54
2         fullname words              9
3   nums/length fullname             25
4         name==username              2
5     description length            104
6           external URL              2
7                private              2
8                 #posts            193
9             #followers            372
10              #follows            400
11                  fake              2

In [24]:
for column in train_df.columns:

    print(
        f"{column:<35} "
        f"{train_df[column].nunique()} unique values"
    )

profile pic                         2 unique values
nums/length username                54 unique values
fullname words                      9 unique values
nums/length fullname                25 unique values
name==username                      2 unique values
description length                  104 unique values
external URL                        2 unique values
private                             2 unique values
#posts                              193 unique values
#followers                          372 unique values
#follows                            400 unique values
fake                                2 unique values

In [25]:
train_df.describe()

,profile pic,nums/length username,fullname words,nums/length fullname,name==username,description length,external URL,private,#posts,#followers,#follows,fake
count,576.000000,576.000000,576.000000,576.000000,576.000000,576.000000,576.000000,576.000000,576.000000,5.760000e+02,576.000000,576.000000
mean,0.701389,0.163837,1.460069,0.036094,0.034722,22.623264,0.116319,0.381944,107.489583,8.530724e+04,508.381944,0.500000
std,0.458047,0.214096,1.052601,0.125121,0.183234,37.702987,0.320886,0.486285,402.034431,9.101485e+05,917.981239,0.500435
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
25%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.900000e+01,57.500000,0.000000
50%,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,1.505000e+02,229.500000,0.500000
75%,1.000000,0.310000,2.000000,0.000000,0.000000,34.000000,0.000000,1.000000,81.500000,7.160000e+02,589.500000,1.000000
max,1.000000,0.920000,12.000000,1.000000,1.000000,150.000000,1.000000,1.000000,7389.000000,1.533854e+07,7500.000000,1.000000

In [26]:
train_df.describe(include="all").T

,count,mean,std,min,25%,50%,75%,max
profile pic,576.0,0.701389,0.458047,0.0,0.0,1.0,1.00,1.00
nums/length username,576.0,0.163837,0.214096,0.0,0.0,0.0,0.31,0.92
fullname words,576.0,1.460069,1.052601,0.0,1.0,1.0,2.00,12.00
nums/length fullname,576.0,0.036094,0.125121,0.0,0.0,0.0,0.00,1.00
name==username,576.0,0.034722,0.183234,0.0,0.0,0.0,0.00,1.00
description length,576.0,22.623264,37.702987,0.0,0.0,0.0,34.00,150.00
external URL,576.0,0.116319,0.320886,0.0,0.0,0.0,0.00,1.00
private,576.0,0.381944,0.486285,0.0,0.0,0.0,1.00,1.00
#posts,576.0,107.489583,402.034431,0.0,0.0,9.0,81.50,7389.00
#followers,576.0,85307.236111,910148.457657,0.0,39.0,150.5,716.00,15338538.00
#follows,576.0,508.381944,917.981239,0.0,57.5,229.5,589.50,7500.00
fake,576.0,0.500000,0.500435,0.0,0.0,0.5,1.00,1.00

In [27]:
if "Fake" in train_df.columns:

    print("✅ 'Fake' target column found!")

else:

    print("⚠️ 'Fake' column not found.")

    print("\nAvailable columns:")
    print(train_df.columns.tolist())

⚠️ 'Fake' column not found.

Available columns:
['profile pic', 'nums/length username', 'fullname words', 'nums/length fullname', 'name==username', 'description length', 'external URL', 'private', '#posts', '#followers', '#follows', 'fake']

In [29]:
if "Fake" in train_df.columns:

    target_counts = train_df["Fake"].value_counts()

    print("Target Distribution")
    print("===================")

    print(target_counts)

In [30]:
if "Fake" in train_df.columns:

    target_percentage = (
        train_df["Fake"]
        .value_counts(normalize=True)
        * 100
    )

    print("Target Percentage")
    print("=================")

    print(target_percentage)

In [31]:
if "Fake" in train_df.columns:

    target_summary = pd.DataFrame({
        "Count": train_df["Fake"].value_counts(),
        "Percentage": (
            train_df["Fake"]
            .value_counts(normalize=True)
            * 100
        ).round(2)
    })

    target_summary

In [32]:
for column in train_df.columns:

    print("\n" + "=" * 60)
    print(f"COLUMN: {column}")
    print("=" * 60)

    print(train_df[column].head(10).to_string(index=False))

============================================================
COLUMN: profile pic
============================================================
1
1
1
1
1
1
1
1
1
1

============================================================
COLUMN: nums/length username
============================================================
0.27
0.00
0.10
0.00
0.00
0.00
0.00
0.00
0.00
0.00

============================================================
COLUMN: fullname words
============================================================
0
2
2
1
2
4
2
2
0
2

============================================================
COLUMN: nums/length fullname
============================================================
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

============================================================
COLUMN: name==username
============================================================
0
0
0
0
0
0
0
0
0
0

============================================================
COLUMN: description length
============================================================
53
44
 0
82
 0
81
50
 0
71
40

============================================================
COLUMN: external URL
============================================================
0
0
0
0
0
1
0
0
0
1

============================================================
COLUMN: private
============================================================
0
0
1
0
1
0
0
0
0
0

============================================================
COLUMN: #posts
============================================================
 32
286
 13
679
  6
344
 16
 33
 72
213

============================================================
COLUMN: #followers
============================================================
  1000
  2740
   159
   414
   151
669987
   122
  1078
  1824
 12945

============================================================
COLUMN: #follows
============================================================
 955
 533
  98
 651
 126
 150
 177
  76
2713
 813

============================================================
COLUMN: fake
============================================================
0
0
0
0
0
0
0
0
0
0

In [33]:
numeric_columns = train_df.select_dtypes(
    include=np.number
).columns.tolist()

print("Numerical Columns")
print("=================")

for column in numeric_columns:
    print("-", column)

Numerical Columns
=================
- profile pic
- nums/length username
- fullname words
- nums/length fullname
- name==username
- description length
- external URL
- private
- #posts
- #followers
- #follows
- fake

In [34]:
categorical_columns = train_df.select_dtypes(
    exclude=np.number
).columns.tolist()

print("Categorical / Text Columns")
print("=========================")

for column in categorical_columns:
    print("-", column)

Categorical / Text Columns
=========================

In [35]:
if len(numeric_columns) > 0:

    numeric_summary = pd.DataFrame({
        "Minimum": train_df[numeric_columns].min(),
        "Maximum": train_df[numeric_columns].max(),
        "Mean": train_df[numeric_columns].mean(),
        "Median": train_df[numeric_columns].median()
    })

    numeric_summary

In [36]:
if len(numeric_columns) > 1:

    correlation = train_df[numeric_columns].corr()

    correlation

In [37]:
dataset_report = pd.DataFrame({
    "Column": train_df.columns,
    "Data Type": [
        str(train_df[column].dtype)
        for column in train_df.columns
    ],
    "Missing Values": [
        train_df[column].isnull().sum()
        for column in train_df.columns
    ],
    "Missing %": [
        round(
            train_df[column].isnull().mean() * 100,
            2
        )
        for column in train_df.columns
    ],
    "Unique Values": [
        train_df[column].nunique()
        for column in train_df.columns
    ]
})

dataset_report

                  Column Data Type  Missing Values  Missing %  Unique Values
0            profile pic     int64               0        0.0              2
1   nums/length username   float64               0        0.0             54
2         fullname words     int64               0        0.0              9
3   nums/length fullname   float64               0        0.0             25
4         name==username     int64               0        0.0              2
5     description length     int64               0        0.0            104
6           external URL     int64               0        0.0              2
7                private     int64               0        0.0              2
8                 #posts     int64               0        0.0            193
9             #followers     int64               0        0.0            372
10              #follows     int64               0        0.0            400
11                  fake     int64               0        0.0              2

In [38]:
print("=" * 60)
print("        AUTHENTISCORE - DATASET INSPECTION")
print("=" * 60)

print("\nDataset:")
print("Instagram Fake Spammer / Genuine Accounts")

print("\nRows:", train_df.shape[0])
print("Columns:", train_df.shape[1])

print("\nDuplicate Rows:", train_df.duplicated().sum())

print("\nTotal Missing Values:",
      train_df.isnull().sum().sum())

print("\nNumerical Columns:",
      len(numeric_columns))

print("Text/Categorical Columns:",
      len(categorical_columns))

print("\nColumn Names:")
for column in train_df.columns:
    print("  -", column)

if "Fake" in train_df.columns:

    print("\nTarget Distribution:")
    print(train_df["Fake"].value_counts())

print("\n" + "=" * 60)
print("        INSPECTION COMPLETE")
print("=" * 60)

============================================================
        AUTHENTISCORE - DATASET INSPECTION
============================================================

Dataset:
Instagram Fake Spammer / Genuine Accounts

Rows: 576
Columns: 12

Duplicate Rows: 2

Total Missing Values: 0

Numerical Columns: 12
Text/Categorical Columns: 0

Column Names:
  - profile pic
  - nums/length username
  - fullname words
  - nums/length fullname
  - name==username
  - description length
  - external URL
  - private
  - #posts
  - #followers
  - #follows
  - fake

============================================================
        INSPECTION COMPLETE
============================================================

In [39]:
REPORT_PATH = "../data/processed/dataset_inspection_report.csv"

dataset_report.to_csv(
    REPORT_PATH,
    index=False
)

print("✅ Inspection report saved to:")
print(REPORT_PATH)

✅ Inspection report saved to:
../data/processed/dataset_inspection_report.csv

In [40]:
train_df["fake"].value_counts()

fake
0    288
1    288
Name: count, dtype: int64

In [41]:
train_df["fake"].value_counts(normalize=True) * 100

fake
0    50.0
1    50.0
Name: proportion, dtype: float64